title: Book Of The Neurokraken
author: The Neuroraken developers
logo: images/book.png
copyright: "CC0 (2025)" # "" to just remove that line

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# execute:
#   execute_notebooks: force

exclude_patterns:
 [README.md, ]

# Information about where the book exists on the web
repository:
  url: https://github.com/PasseckerLab/Neurokraken  # Online location of the book
  path_to_book: ./  # Optional path to your book, relative to the repository root
  branch: main      # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

# enable mermaid support - For the build to work you also need to:
# pip install sphinxcontrib-mermaid 
sphinx:
  extra_extensions:
  - sphinxcontrib.mermaid